### PR TITLE
Ct5 up 361/update webpack config dependencies

### PR DESCRIPTION
**Pull request by briandipalma**
Several JIRAs in this PR CT5UP-230, CT5UP-311, CT5UP-405 and CT5UP-361 as they are all backward breaking changes that would require a major version rev they are being bundled into one PR.

### CODE REVIEW

**Comment by briandipalma** [comment]
We are also removing PhantomJS support in this PR, there is no JIRA for that task.

**Comment by thecapdan** [comment]
Hi Brian.

There's a problem with the sass loaded in the cli tempalte app. Getting this error when running loading the app in dev:

```
./src/index.scss
Module build failed:
$fontsize: 20px;
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in C:\development\temp\caplin-dev-tools\cli\woa\apps\wooly\src\index.scss (line 1, column 1)
```

**Comment by briandipalma** [comment]
@thecapdan It looks OK now, I updated the dependencies of the templates.

**Comment by thecapdan** [comment]
thanks @briandipalma . working now

**Pull request merged**
