### PR TITLE
adding default class and example test to template to encourage this s…

### PR DESCRIPTION
**Pull request by thecapdan**
…tructure for blank components

### CODE REVIEW

**Comment by briandipalma** [comment]
Will we be adding Jest as the testing tool or is that still in the air?

**Comment by thecapdan** [comment]
Gonna take a dev day to try out jest and weigh up the pros/cons. Possibly tomorrow

**Comment by briandipalma** [comment]
Will I merge this in the meantime?

**Comment by thecapdan** [comment]
Sure. I'll merge now. Can update later if we change to jest

**Pull request merged**
